config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users
  resources :roles
  resources :countries
  resources :profiles
  resources :comments, only: [:index, :show, :new, :edit, :create, :update, :destroy]  # Top-level comments

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :profiles
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  belongs_to :status, optional: true
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :country, optional: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :posts
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_one :profile
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all.includes(:user, :post)
  end

  def show; end

  def new
    @comment = Comment.new
  end

  def edit; end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to @comment, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:post_id, :user_id, :content)
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  def index
    @countries = Country.all
  end

  def show; end

  def new
    @country = Country.new
  end

  def edit; end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to @country, notice: 'Country was successfully created.'
    else
      render :new
    end
  end

  def update
    if @country.update(country_params)
      redirect_to @country, notice: 'Country was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @country.destroy
    redirect_to countries_url, notice: 'Country was successfully destroyed.'
  end

  private

  def set_country
    @country = Country.find(params[:id])
  end

  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all.includes(:user, :category, :status, :tags)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :title, :content, :category_id, :status_id, tag_ids: [])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all.includes(:user, :country)
  end

  def show; end

  def new
    @profile = Profile.new
  end

  def edit; end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:user_id, :country_id, :biography)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show; end

  def new
    @role = Role.new
  end

  def edit; end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id, "Пост" %>
    <%= form.collection_select :post_id, Post.all, :id, :title, prompt: "Select Post" %>
  </div>

  <div class="field">
    <%= form.label :user_id, "Пользователь" %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: "Select User" %>
  </div>

  <div class="field">
    <%= form.label :content, "Содержимое" %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Изменить комментарий</h1>
<%= render 'form', comment: @comment %>
<%= button_to 'Назад', comments_path, method: :get, form: { class: 'inline-button' } %>

app/views/comments/index.html.erb
<h1>Комментарии</h1>
<table>
  <thead>
    <tr>
      <th>Пост</th>
      <th>Пользователь</th>
      <th>Содержимое</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post.title %></td>
        <td><%= comment.user.name %></td>
        <td><%= comment.content %></td>
        <td><%= button_to 'Показать', comment, method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Изменить', edit_comment_path(comment), method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Удалить', comment, method: :delete, data: { confirm: 'Are you sure?' }, form: { class: 'inline-button' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'Добавить комментарий', new_comment_path, method: :get, form: { class: 'inline-button' } %>

app/views/comments/new.html.erb
<h1>Добавить комментарий</h1>
<%= render 'form', comment: @comment %>
<%= button_to 'Назад', comments_path, method: :get, form: { class: 'inline-button' } %>

app/views/comments/show.html.erb
<h1>Комментарий</h1>
<p>
  <strong>Пост:</strong> <%= @comment.post.title %>
</p>
<p>
  <strong>Пользователь:</strong> <%= @comment.user.name %>
</p>
<p>
  <strong>Содержимое:</strong> <%= @comment.content %>
</p>
<%= button_to 'Изменить', edit_comment_path(@comment), method: :get, form: { class: 'inline-button' } %>
<%= button_to 'Назад', comments_path, method: :get, form: { class: 'inline-button' } %>

app/views/countries/_form.html.erb
<%= form_with(model: @country, local: true) do |form| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>
      <ul>
        <% @country.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Изменить страну</h1>
<%= render 'form', country: @country %>
<%= button_to 'Назад', countries_path, method: :get, form: { class: 'inline-button' } %>

app/views/countries/index.html.erb
<h1>Страны</h1>
<table>
  <thead>
    <tr>
      <th>Имя</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= button_to 'Показать', country, method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Изменить', edit_country_path(country), method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Удалить', country, method: :delete, data: { confirm: 'Are you sure?' }, form: { class: 'inline-button' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'Добавить страну', new_country_path, method: :get, form: { class: 'inline-button' } %>

app/views/countries/new.html.erb
<h1>Добавить страну</h1>
<%= render 'form', country: @country %>
<%= button_to 'Назад', countries_path, method: :get, form: { class: 'inline-button' } %>

app/views/countries/show.html.erb
<h1>Страна: <%= @country.name %></h1>
<%= button_to 'Изменить', edit_country_path(@country), method: :get, form: { class: 'inline-button' } %>
<%= button_to 'Назад', countries_path, method: :get, form: { class: 'inline-button' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'NNTU.png', rel: 'icon', type: 'image/png' %>
    <title>Sharkfin by ChausovND</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%# For Rails 7 with Import Maps. If you are using Webpacker (Rails 6), replace with javascript_pack_tag accordingly %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= button_to 'Посты', posts_path, method: :get, form: { class: 'nav-button' } %>
      <%= button_to 'Роли', roles_path, method: :get, form: { class: 'nav-button' } %>
      <%= button_to 'Страны', countries_path, method: :get, form: { class: 'nav-button' } %>
      <%= button_to 'Профили', profiles_path, method: :get, form: { class: 'nav-button' } %>
      <%= button_to 'Комментарии', comments_path, method: :get, form: { class: 'nav-button' } %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id, "Автор" %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: "Выберите автора" %>
  </div>

  <div class="field">
    <%= form.label :title, "Название" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content, "Содержимое" %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :category_id, "Категория" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Выберите категорию" %>
  </div>

  <div class="field">
    <%= form.label :status_id, "Статус" %>
    <%= form.collection_select :status_id, Status.all, :id, :name, prompt: "Выберите статус" %>
  </div>

  <div class="field">
    <%= form.label :tag_ids, "Тэги" %>
    <%= form.collection_select :tag_ids, Tag.all, :id, :name, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Изменить пост</h1>
<%= render 'form', post: @post %>
<%= button_to 'Назад', posts_path, method: :get, form: { class: 'inline-button' } %>

app/views/posts/index.html.erb
<h1>Посты</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Автор</th>
      <th>Категория</th>
      <th>Статус</th>
      <th>Тэги</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.user.name %></td>
        <td><%= post.category&.name %></td>
        <td><%= post.status&.name %></td>
        <td><%= post.tags.map(&:name).join(", ") %></td>
        <td><%= button_to 'Показать', post, method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Изменить', edit_post_path(post), method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Удалить', post, method: :delete, data: { confirm: 'Are you sure?' }, form: { class: 'inline-button' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Добавить пост', new_post_path, method: :get, form: { class: 'inline-button' } %>

app/views/posts/new.html.erb
<h1>Добавить пост</h1>
<%= render 'form', post: @post %>
<%= button_to 'Назад', posts_path, method: :get, form: { class: 'inline-button' } %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <strong>Автор:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Категория:</strong>
  <%= @post.category&.name %>
</p>

<p>
  <strong>Статус:</strong>
  <%= @post.status&.name %>
</p>

<p>
  <strong>Содержимое:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Тэги:</strong>
  <%= @post.tags.map(&:name).join(", ") %>
</p>

<%= button_to 'Изменить', edit_post_path(@post), method: :get, form: { class: 'inline-button' } %>
<%= button_to 'Назад', posts_path, method: :get, form: { class: 'inline-button' } %>

app/views/profiles/_form.html.erb
<%= form_with(model: @profile, local: true) do |form| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id, "Пользователь" %>
    <%= form.collection_select :user_id, User.all, :id, :name, prompt: "Выберите пользователя" %>
  </div>

  <div class="field">
    <%= form.label :country_id, "Страна" %>
    <%= form.collection_select :country_id, Country.all, :id, :name, prompt: "Выберите страну" %>
  </div>

  <div class="field">
    <%= form.label :biography, "Описание" %>
    <%= form.text_area :biography %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Изменить профиль</h1>
<%= render 'form', profile: @profile %>
<%= button_to 'Назад', profiles_path, method: :get, form: { class: 'inline-button' } %>

app/views/profiles/index.html.erb
<h1>Профили</h1>
<table>
  <thead>
    <tr>
      <th>Пользователь</th>
      <th>Страна</th>
      <th>Описание</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user.name %></td>
        <td><%= profile.country&.name %></td>
        <td><%= profile.biography %></td>
        <td><%= button_to 'Показать', profile, method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Изменить', edit_profile_path(profile), method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Удалить', profile, method: :delete, data: { confirm: 'Are you sure?' }, form: { class: 'inline-button' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'Добавить профиль', new_profile_path, method: :get, form: { class: 'inline-button' } %>

app/views/profiles/new.html.erb
<h1>Добавить профиль</h1>
<%= render 'form', profile: @profile %>
<%= button_to 'Назад', profiles_path, method: :get, form: { class: 'inline-button' } %>

app/views/profiles/show.html.erb
<h1>Профиль пользователя <%= @profile.user.name %></h1>
<p>
  <strong>Страна:</strong> <%= @profile.country&.name %>
</p>
<p>
  <strong>Описание:</strong> <%= @profile.biography %>
</p>
<%= button_to 'Изменить', edit_profile_path(@profile), method: :get, form: { class: 'inline-button' } %>
<%= button_to 'Назад', profiles_path, method: :get, form: { class: 'inline-button' } %>

app/views/roles/_form.html.erb
<%= form_with(model: @role, local: true) do |form| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>
      <ul>
        <% @role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Название" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Изменить роль</h1>
<%= render 'form', role: @role %>
<%= button_to 'Назад', roles_path, method: :get, form: { class: 'inline-button' } %>

app/views/roles/index.html.erb
<h1>Роли</h1>
<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= button_to 'Показать', role, method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Изменить', edit_role_path(role), method: :get, form: { class: 'inline-button' } %></td>
        <td><%= button_to 'Удалить', role, method: :delete, data: { confirm: 'Are you sure?' }, form: { class: 'inline-button' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'Добавить роль', new_role_path, method: :get, form: { class: 'inline-button' } %>

app/views/roles/new.html.erb
<h1>Добавить роль</h1>
<%= render 'form', role: @role %>
<%= button_to 'Назад', roles_path, method: :get, form: { class: 'inline-button' } %>

app/views/roles/show.html.erb
<h1>Роль: <%= @role.name %></h1>
<%= button_to 'Изменить', edit_role_path(@role), method: :get, form: { class: 'inline-button' } %>
<%= button_to 'Назад', roles_path, method: :get, form: { class: 'inline-button' } %>